Refine AppWrapper phases and lifecycle
project-codeflare/appwrapper pull request #16
Opened 2024-02-09 20:42 UTC by dgrove-oss

Encode status of child resources via Conditions.
Consolidate and rename Phases.

2024-02-09 22:09 UTC, tardieu requested changes

2024-02-09 22:09 UTC, tardieu commented on api/v1beta2/appwrapper_types.go
> +	PassiveResources AppWrapperCondition = "PassiveResources"
As named these two conditions sound like opposites, which is not the intent. I suggest we rename the two conditions to make it obvious that:
- one condition is about quota reservation: if false then the appwrapper is not using quota,
- one condition is about deployed resources: if false then there are no wrapped objects deployed on the cluster.

2024-02-09 23:27 UTC, dgrove-oss commented on internal/controller/appwrapper_controller.go
> +// [aw-states]: https://github.com/dgrove-oss/appwrapper/blob/crd/docs/state-diagram.md
changed to project-codeflare.

2024-02-09 23:39 UTC, dgrove-oss commented
Ready for another review.

2024-02-10 00:42 UTC, tardieu approved these changes
lgtm

In the "terminating" state, it looks like we could update the two conditions in one api call, but this can be improved in a separate PR.

2024-02-10 22:08 UTC, dgrove-oss commented
> lgtm
> 
> In the "terminating" state, it looks like we could update the two conditions in one api call, but this can be improved in a separate PR.

done.

2024-02-10 22:12 UTC, merged